name: AccountGuard
version: '${version}'
description: '${description}'
author: '${author}'
main: me.adrigamer2950.accountguard.bukkit.AGBukkit
api-version: '1.18'
website: https://github.com/Adrigamer2950/AccountGuard
folia-supported: true

depend:
  - AdriAPI

libraries:
  - dev.dejvokep:boosted-yaml:1.3.6
  - com.h2database:h2:2.2.220

commands:
  ag:
    description: Main command
    usage: /ag help

permissions:
  accountguard.*:
    default: false
    children:
      accountguard.reload:
        default: false
      accountguard.add.own:
        default: false
      accountguard.add.other:
        default: false
      accountguard.remove.own:
        default: false
      accountguard.remove.other:
        default: false
      accountguard.list.own:
        default: false
      accountguard.list.other:
        default: false
