name: AccountGuard
version: '${version}'
description: '${description}'
author: '${author}'
main: me.adrigamer2950.accountguard.bukkit.AGBukkit
api-version: '1.18'
website: https://github.com/Adrigamer2950/AccountGuard
folia-supported: true

depend:
  - AdriAPI

libraries:
  - dev.dejvokep:boosted-yaml:1.3.6

commands:
  ag:
    description: Main command
    usage: /ag help
