name: AccountGuard
version: '${version}'
main: me.adrigamer2950.accountguard.bukkit.AGBukkit
api-version: '1.13'
author: Adrigamer2950
website: https://github.com/Adrigamer2950/AccountGuard
description: "Protect your users/staff accounts from being hacked and misused on your server as easily as ever"
load: STARTUP
folia-supported: true

depend:
  - AdriAPI

commands:
  accountguard:
    aliases:
      - ag
    usage: "§c/ag help"
    description: Main command for AccountGuard plugin

permissions:
  accountguard.*:
    default: false
    description: "Gives all permissions"
    children:
      accountguard.admin.reload:
        default: false
        description: "Gives permission to use '/ag reload' command"
      accountguard.admin.add:
        default: false
        description: "Gives permission to use '/ag add' command"
      accountguard.admin.remove:
        default: false
        description: "Gives permission to use '/ag remove' command"
      accountguard.admin.list:
        default: false
        description: "Gives permission to use '/ag list' command"
      accountguard.command:
        default: true
        description: "Gives permission to use '/ag' command"