name: Build

on: [
  workflow_dispatch,
  push
]

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      BUILD_NUMBER: "${{ github.run_number }}"
      COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"

    steps:
      - uses: actions/checkout@v4
        name: Checkout sources

      - uses: actions/setup-java@v4
        name: Set up JDK 17
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4
        name: Setup Gradle

      - name: Build Artifact
        run: "chmod +x ./gradlew && ./gradlew build $([[ \"$COMMIT_MESSAGE\" == \"release:\"* ]] && echo || echo -PBUILD_NUMBER=$BUILD_NUMBER)"

      - uses: actions/upload-artifact@v4
        name: Save Artifact
        with:
          name: "AccountGuard-b${{ github.run_number }}"
          path: build/libs/*.jar

      - name: Publish Artifact
        if: github.repository == 'Adrigamer2950/AccountGuard'
        env:
          NEXUS_USERNAME: "${{ secrets.NEXUS_USERNAME }}"
          NEXUS_PASSWORD: "${{ secrets.NEXUS_PASSWORD }}"
        run: "./gradlew :api:publish -PNEXUS_USERNAME=$NEXUS_USERNAME -PNEXUS_PASSWORD=$NEXUS_PASSWORD $([[ \"$COMMIT_MESSAGE\" == \"release:\"* ]] && echo \"\" || echo \"-PBUILD_NUMBER=$BUILD_NUMBER\")"
